baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "vector"

[params]
  administrationURL = "https://docs.vectorproject.io/usage/administration"
  agentRoleURL = "https://app.gitbook.com/@timber/s/vector/setup/deployment/roles/agent"
  backupsURL = "https://docs.vectorproject.io/use-cases/backups"
  betaURL = "https://vectorproject.typeform.com/to/wV0DC8"
  comparisonsURL = "https://docs.vectorproject.io/comparisons"
  conceptsURL = "https://docs.vectorproject.io/about/concepts"
  configurationURL = "https://docs.vectorproject.io/usage/configuration"
  correctnessURL = "https://docs.vectorproject.io/comparisons/correctness"
  costURL = "https://docs.vectorproject.io/use-cases/cost"
  deploymentURL = "https://docs.vectorproject.io/setup/deployment"
  docsURL = "https://docs.vectorproject.io/"
  downloadURL = "https://github.com/timberio/vector/releases"
  getStartedURL = "https://docs.vectorproject.io/setup/getting-started"
  governanceURL = "https://docs.vectorproject.io/use-cases/governance"
  guidesURL = "https://docs.vectorproject.io/usage/guides"
  installURL = "https://docs.vectorproject.io/setup/installation"
  lockinURL = "https://docs.vectorproject.io/use-cases/lock-in"
  logsToMetricsURL = "https://docs.vectorproject.io/usage/configuration/transforms/log_to_metric"
  luaURL = "https://docs.vectorproject.io/usage/configuration/transforms/lua"
  multiCloudURL = "https://docs.vectorproject.io/use-cases/multi-cloud"
  performanceURL = "https://docs.vectorproject.io/comparisons/performance"
  repoURL = "https://github.com/timberio/vector"
  roadmapURL = "https://github.com/timberio/vector/milestones?direction=asc&sort=title&state=open"
  securityURL = "https://docs.vectorproject.io/use-cases/security"
  serviceRoleURL = "https://app.gitbook.com/@timber/s/vector/setup/deployment/roles/service"
  sinksURL = "https://docs.vectorproject.io/usage/configuration/sinks"
  sourcesURL = "https://docs.vectorproject.io/usage/configuration/sources"
  subscribeActionURL = "https://app.getvero.com/forms/a748ded7ce0da69e6042fa1e21042506"
  topologiesURL = "https://docs.vectorproject.io/setup/deployment/topologies"
  transformsURL = "https://docs.vectorproject.io/usage/configuration/transforms"
  usecasesURL = "https://docs.vectorproject.io/use-cases"